- name: restart mysql service
  become: true
  systemd:
    name: mysql
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes