- name: create directories
  file:
    path: "{{ mse_host_config_dir }}"
    state: directory
    mode: 0755

- name: copy mysql exporter config 
  template:
    src: ".my.cnf.j2"
    dest: "{{ mse_host_config_dir }}/.my.cnf"
    owner: "{{ mse_host_user_name }}"
    group: "{{ mse_host_user_name }}"
  notify: 
  - restart mysql exporter service

- name: copy service config
  template:
    src: "mysql_exporter.service.j2"
    dest: "/etc/systemd/system/{{ mse_service_name }}.service"
    mode: 0644
  notify: 
  - reload systemd

- name: restart mysql exporter service
  become: true
  systemd:
    name: "{{ mse_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
