- name: stop mysql exporter service
  systemd:
    name: "{{ mse_service_name }}"
    enabled: false
    state: stopped

- name: delete directory
  file:
    path: "{{ mse_host_config_dir }}"
    state: absent

- name: delete mysql exporter config
  file:
    path: "/etc/systemd/system/{{ mse_service_name }}.service"
    state: absent
  notify: 
  - reload systemd
