- name: create directories
  file:
    path: "{{ msq_host_db_dir }}"
    state: directory
    mode: 0755

- name: copy service config
  template:
    src: "mysql.service.j2"
    dest: "/etc/systemd/system/{{ msq_service_name }}.service"
    mode: 0644
  notify: 
  - reload systemd

- name: restart mysql service
  become: true
  systemd:
    name: "{{ msq_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes