global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
         - 192.168.1.190:9090
  - job_name: 'node'
    static_configs:
      - targets:
         - 192.168.1.190:9100
  - job_name: 'mysql'
    static_configs:
      - targets:
         - 192.168.1.190:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.190:9104
  - job_name: 'cadvisor'
    static_configs:
      - targets:
         - 192.168.1.190:8080
  - job_name: 'es-exporter'
    static_configs:
      - targets:
         - 192.168.1.190:19200
