- name: stop grafana service
  systemd:
    name: "{{ gr_service_name }}"
    enabled: false
    state: stopped

- name: delete directories
  file:
    path: "{{ gr_host_config_dir }}"
    state: absent

- name: delete grafana config
  file:
    path: "/etc/systemd/system/{{ gr_service_name }}.service"
    state: absent
  notify: 
  - reload systemd
