- name: stop logstash service
  systemd:
    name: "{{ lg_service_name }}"
    enabled: false
    state: stopped

- name: delete directories
  file:
    path: "{{ lg_host_config_dir }}"
    state: absent

- name: delete logstash config
  file:
    path: "/etc/systemd/system/{{ lg_service_name }}.service"
    state: absent
  notify: 
  - reload systemd
