- name: restart logstash service
  become: true
  systemd:
    name: "{{ lg_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes
