global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
         - <localhost>:9090
  - job_name: 'node'
    static_configs:
      - targets:
         - <localhost>:9100
  - job_name: 'mysql'
    static_configs:
      - targets:
         - <localhost>:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <localhost>:9104
  - job_name: 'cadvisor'
    static_configs:
      - targets:
         - <localhost>:8080
  - job_name: 'es-exporter'
    static_configs:
      - targets:
         - <localhost>:19200