- name: stop prometheus service
  systemd:
    name: "{{ pr_service_name }}"
    enabled: false
    state: stopped

- name: delete directories
  file:
    path: "{{ pr_host_config_dir }}"
    state: absent

- name: delete prometheus config
  file:
    path: "/etc/systemd/system/{{ pr_service_name }}.service"
    state: absent
  notify: 
  - reload systemd
